[log]
level = "debug"

[database]
dsn = "user=postgres password=postgres host=localhost port=5432 dbname=oj_lab sslmode=disable TimeZone=Asia/Shanghai"

[redis]
hosts = ["localhost:6379"]

[jwt]
secret = "example_secret"
duration = "24h"

[service]
force_console_color = true
auth_on = true
port = ":8080"
cookie.age = "24h"
mode = "debug"
swagger_on = true
frontend_dist = "workdirs/development/frontend_dist"

[rpc-server]
port = 50051

[minio]
endpoint = "localhost:9000"
accessKeyID = "minio-root-user"
secretAccessKey = "minio-root-password"
useSSL = false
bucketName = "oj-lab-problem-package"
